<h3 class="page-title">Dish feedback</h3>

<link type="text/css" rel="stylesheet" href="/assets/plugins/jquery-datatable/media/css/jquery.dataTables.css">
<link type="text/css" rel="stylesheet" href="/assets/plugins/jquery-datatable/extensions/FixedColumns/css/dataTables.fixedColumns.min.css">
<link type="text/css" rel="stylesheet" href="/pages/css/pages.css">
<link media="screen" type="text/css" rel="stylesheet" href="/assets/plugins/datatables-responsive/css/datatables.responsive.css">

<script type="text/javascript" src="/assets/plugins/jquery-datatable/media/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="/assets/plugins/jquery-datatable/extensions/TableTools/js/dataTables.tableTools.min.js"></script>
<script src="/assets/plugins/datatables-responsive/js/datatables.responsive.js" type="text/javascript"></script>
<script src="/assets/plugins/datatables-responsive/js/lodash.min.js" type="text/javascript"></script>
<table id="tableWithDynamicRows" class="table table-hover demo-table-dynamic dataTable no-footer" role="grid" aria-describedby="tableWithDynamicRows_info">
	<thead>
		<tr role="row">
			<th class="sorting_asc" tabindex="0" aria-controls="tableWithDynamicRows" rowspan="1" colspan="1" style="width: 20px;" aria-sort="ascending">
				ID
			</th>
			<th class="sorting" tabindex="0" aria-controls="tableWithDynamicRows" rowspan="1" colspan="1" style="width: 416px;">
				Dish
			</th>
			<th class="sorting" tabindex="0" aria-controls="tableWithDynamicRows" rowspan="1" colspan="1" style="width: 266px;">
				Photo
			</th>
			<th class="sorting" tabindex="0" aria-controls="tableWithDynamicRows" rowspan="1" colspan="1" style="width: 266px;">
				Comment
			</th>
			<th tabindex="0" aria-controls="tableWithDynamicRows" rowspan="1" colspan="1" style="width: 341px;">
				Taste
			</th>
			<th tabindex="0" aria-controls="tableWithDynamicRows" rowspan="1" colspan="1" style="width: 341px;">
				Satiety
			</th>
			<th tabindex="0" aria-controls="tableWithDynamicRows" rowspan="1" colspan="1" style="width: 341px;">
				Quality
			</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($rows as $row) {?>
    		<tr role="row" class="odd" data-id="<?= $row->id()?>">
    			<td class="v-align-middle sorting_1">
    				<p><?= $row->id()?></p>
    			</td>
    			<td class="v-align-middle" role="name">
    				<p><?= $row->Dish_Table->name()?></p>
    			</td>
    			<td class="v-align-middle">
    				<?php $rowLogo = $row->Media_Table;
    				if ($rowLogo){?>
        				<img src="<?= $row->Media_Table->path()?>" style="width: auto; height: 100px;">
					<?php }?>
    			</td>
    			<td class="v-align-middle">
    				<p><?= $row->comment()?></p>
    			</td>
    			<td class="v-align-middle">
    				<p><?= $row->taste()?></p>
    			</td>
    			<td class="v-align-middle">
    				<p><?= $row->satiety()?></p>
    			</td>
    			<td class="v-align-middle">
    				<p><?= $row->quality()?></p>
    			</td>
    		</tr>
		<?php }?>
	</tbody>
</table>

<script>
    var tableElem = $('#tableWithDynamicRows');
    
    var settings = {
        "sDom": "<'table-responsive't><'row'<p i>>",
        "destroy": true,
        "scrollCollapse": true,
        "oLanguage": {
            "sLengthMenu": "_MENU_ ",
            "sInfo": "Showing <b>_START_ to _END_</b> of _TOTAL_ entries"
        },
        "iDisplayLength": 5
    };
    
    tableElem.dataTable(settings);
</script>