<?= Phalcon\Tag::javascriptInclude('pages/js/pages.min.js');?>
<form role="form" id="addFormCompany">
  <div class="row">
    <div class="col-sm-12">
      <div class="form-group form-group-default required">
        <label>Name</label>
        <input name="name" type="text" class="form-control" required>
      </div>
    </div>
  </div>
  <div class="row">
  	<div class="col-sm-12">
      <div class="form-group form-group-default required">
        <label>Logo</label>
        <input name="logo" type="text" class="form-control" required>
      </div>
    </div>
  </div>
  <div class="row">
  	<div class="col-sm-12">
        <input type="hidden" id="mySelect2" class="full-width">
    </div>
  </div>
  <button class="hide" type="submit"></button>
</form>

<script>
	function categorySelect()
	{
		var data = [];
		<?php foreach ($rowsCategory as $category) {?>
			data.push({id: <?= $category->id()?>, text: '<?= $category->name()?>'})
		<?php }?>

		return data;
	}

    $("#mySelect2").select2({
        placeholder: "Category",
        data: categorySelect()
    });

    $('#submitAddCompany').unbind('click');
    $('#submitAddCompany').click(function(){
    	$('#addFormCompany').submit();
    });
    
    $('#addFormCompany').unbind('submit');
    $('#addFormCompany').submit(function(e)
    {
		e.preventDefault();
		url = '/company/add';
		$.post(
			url,
			$(this).serialize(),
			function(data)
			{
				var data = JSON.parse(data)
				table.addRow(data.id, data.name, data.category_id, data.logo, data.datetime_create);
				$('#addModal').modal('hide');
			}
		);
	});
</script>