<?= Phalcon\Tag::javascriptInclude('pages/js/pages.min.js');?>
<?= Phalcon\Tag::javascriptInclude('assets/plugins/jquery-upload/jquery.iframe-transport.js');?>
<?= Phalcon\Tag::javascriptInclude('assets/plugins/jquery-upload/jquery.fileupload.js');?>
<?= Phalcon\Tag::javascriptInclude('assets/plugins/jquery-upload/jquery.ui.widget.js');?>
<form role="form" id="editFormCompany">
	<div class="row">
		<div class="col col-sm-4">
            <div class="logo_jk">
            	<div data-logo_jk="upload" class="logo_jk_upload-wrap">
            		<div class="logo_jk__upload-outer">
            			<div class="vc-m">
            				<div class="vc-i">
            					<span class="logo_jk__upload-text">
            						<span class="logo_jk__upload-icon">Change image</span>
            					</span>
            				</div>
            			</div>
            		</div>
            	</div>
            	<?php $rowMedia = $row->Media_Table;?>
            	<?php $logo = $rowMedia ? $rowMedia->path() : 'https://scontent-frt3-1.cdninstagram.com/hphotos-xft1/t51.2885-19/s150x150/11420849_1597556317176701_1107730959_a.jpg'?>
            	<?php $logoVal = $rowMedia ? $rowMedia->id() : '0'?>
            	<img id="company-logo" src="<?= $logo?>" data-default-src="https://scontent-frt3-1.cdninstagram.com/hphotos-xft1/t51.2885-19/s150x150/11420849_1597556317176701_1107730959_a.jpg" style="width: auto; height: 160px;">
                <input id="logoUpload" name="media" type="file" class="hide" data-url="/media/upload">
                <input id="logo" name="logo" type="text" value="<?= $logoVal?>">
            </div>
		</div>
		<div class="col col-sm-8">
          <div class="row">
              <div class="form-group form-group-default required">
                <label>Name</label>
                <input name="name" type="text" class="form-control" value="<?= $row->name()?>" required>
              </div>
          </div>
          <div class="row">
              <div class="form-group form-group-default required">
                <label>Address</label>
                <input name="address" type="text" class="form-control" required>
              </div>
          </div>
          <div class="row">
          		<div class="form-group">
                	<input type="hidden" id="category" class="full-width" name="category_id" value="<?= $row->categoryId()?>">
                </div>
          </div>
		</div>
	</div>
  <button class="hide" type="submit"></button>
</form>

<script>
	function categorySelect()
	{
		var data = [];
		<?php foreach ($rowsCategory as $category) {?>
			data.push({id: <?= $category->id()?>, text: '<?= $category->name()?>'})
		<?php }?>

		return data;
	}

    $("#category").select2({
        placeholder: "Category",
        data: categorySelect()
    });

    $('#submitEditCompany').unbind('click');
    $('#submitEditCompany').click(function(){
    	$('#editFormCompany button[type="submit"]').trigger('click');
    });
    
    $('#editFormCompany').unbind('submit');
    $('#editFormCompany').submit(function(e)
    {
		e.preventDefault();
		url = '/company/edit?id=<?= $row->id()?>';
		$.post(
			url,
			$(this).serialize(),
			function(data)
			{
				location.reload();
			}
		);
	});

    $('#logoUpload').fileupload({
        dataType: 'json',
        done: function (e, data) {
        	var objImage = data.result;

        	$('#company-logo').attr('src', objImage.path);
        	$('#logo').val(objImage.id);
        }
    });
	
	$('[data-logo_jk="upload"]').click(function(){
		$('#logoUpload').trigger('click');
	});
</script>