<link type="text/css" rel="stylesheet" href="/assets/plugins/jquery-datatable/media/css/jquery.dataTables.css">
<link type="text/css" rel="stylesheet" href="/assets/plugins/jquery-datatable/extensions/FixedColumns/css/dataTables.fixedColumns.min.css">
<link type="text/css" rel="stylesheet" href="/pages/css/pages.css">
<link media="screen" type="text/css" rel="stylesheet" href="/assets/plugins/datatables-responsive/css/datatables.responsive.css">

<script type="text/javascript" src="/assets/plugins/jquery-datatable/media/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="/assets/plugins/jquery-datatable/extensions/TableTools/js/dataTables.tableTools.min.js"></script>
<script src="/assets/plugins/datatables-responsive/js/datatables.responsive.js" type="text/javascript"></script>
<script src="/assets/plugins/datatables-responsive/js/lodash.min.js" type="text/javascript"></script>

<table id="tableWithDynamicRows" class="table table-hover demo-table-dynamic dataTable no-footer" role="grid" aria-describedby="tableWithDynamicRows_info">
	<thead>
		<tr role="row">
			<th class="sorting_asc" tabindex="0" aria-controls="tableWithDynamicRows" rowspan="1" colspan="1" style="width: 1%;" aria-sort="ascending">
				ID
			</th>
			<th class="sorting" tabindex="0" aria-controls="tableWithDynamicRows" rowspan="1" colspan="1">
				Login
			</th>
			<th class="sorting" tabindex="0" aria-controls="tableWithDynamicRows" rowspan="1" colspan="1" style="width: 2%;">
				Password
			</th>
			<th class="sorting" tabindex="0" aria-controls="tableWithDynamicRows" rowspan="1" colspan="1" style="width: 2%;">
				Type
			</th>
			<th class="sorting" tabindex="0" aria-controls="tableWithDynamicRows" rowspan="1" colspan="1" style="width: 2%;">
				E-mail
			</th>
			<th class="sorting" tabindex="0" aria-controls="tableWithDynamicRows" rowspan="1" colspan="1" style="width: 2%;">
				Phone
			</th>
			<th class="sorting" tabindex="0" aria-controls="tableWithDynamicRows" rowspan="1" colspan="1" style="width: 2%;">
				Picture
			</th>
			<th class="sorting" tabindex="0" aria-controls="tableWithDynamicRows" rowspan="1" colspan="1" style="width: 2%;">
				City
			</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($rows as $row) {?>
    		<tr role="row" class="odd" data-id="<?= $row->id()?>">
    			<td class="v-align-middle sorting_1">
    				<p><?= $row->id()?></p>
    			</td>
    			<td class="v-align-middle" role="login">
    				<p><?= $row->login()?></p>
    			</td>
    			<td class="v-align-middle" role="password">
    				<p><?= $row->password()?></p>
    			</td>
    			<td class="v-align-middle" role="type">
    				<p><?= $row->type()?></p>
    			</td>
    			<td class="v-align-middle" role="email">
    				<p><?= $row->email()?></p>
    			</td>
    			<td class="v-align-middle" role="phone">
    				<p><?= $row->phone()?></p>
    			</td>
    			<td class="v-align-middle">
    				<?php $rowLogo = $row->Media_Table;
    				if ($rowLogo){?>
        				<img src="<?= $row->Media_Table->path()?>" style="width: auto; height: 100px;">
					<?php }?>
    			</td>
    			<td class="v-align-middle">
    				<?php $rowCity = $row->City_Table;
    				if ($rowLogo){?>
        				<p><?= $rowCity->name()?></p>
					<?php }?>
    			</td>
    		</tr>
		<?php }?>
	</tbody>
</table>

<script>
var tableElem = $('#tableWithDynamicRows');

var settings = {
    "sDom": "<'table-responsive't><'row'<p i>>",
    "destroy": true,
    "scrollCollapse": true,
    "oLanguage": {
        "sLengthMenu": "_MENU_ ",
        "sInfo": "Showing <b>_START_ to _END_</b> of _TOTAL_ entries"
    },
    "iDisplayLength": 5
};

tableElem.dataTable(settings);


function deleteRow(elem)
{
	var row 	= $(elem).parents('tr');
	var rowId 	= row.data('id');
	var name 	= row.find('td[role="name"] p').text();

	swal(
	{
		title: "Are you sure?",   
		text: 'You will not be able to recover this user "' + name  + '"!',   
		type: "warning",   
		showCancelButton: true,   
		confirmButtonColor: "#f55753",   
		confirmButtonText: "Yes, delete it!",   
		closeOnConfirm: false 
	}, 
	function()
	{
		$.get(
			'/user/delete?id=' + rowId,
			function()
			{
        		swal("Deleted!", 'User "' + name +'" has been deleted.', "success");
        		location.reload();
			}
		);
	});
}
</script>