<h3 class="page-title">Category dish list</h3>

<button type="button" id="btnAdd" class="btn btn-primary btn-cons btn-animated from-left fa fa-plus">
	<span>Add</span>
</button>

<!-- Modal -->
<div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">New category dish</h4>
      </div>
      <div class="modal-body"></div>
      <div class="modal-footer">
        <button id="submitAddCategoryDish" type="button" class="btn btn-primary">Save</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<?php echo $this->partial('categoryDish/grid', $this)?>

<script>
	$('#btnAdd').click(function(){
		$.get(
			'/categoryDish/add',
			function(data)
			{
				$('#addModal .modal-body').html(data);
				$('#addModal').modal('show');
			}
		);
	});
</script>