<head>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <meta charset="utf-8" />
    <title>Administration control</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <link rel="apple-touch-icon" href="image/60.png">
    <link rel="apple-touch-icon" sizes="76x76" href="image/76.png">
    <link rel="apple-touch-icon" sizes="120x120" href="image/120.png">
    <link rel="apple-touch-icon" sizes="152x152" href="image/152.png">
    <link rel="icon" type="image/x-icon" href="favicon.ico" />
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-touch-fullscreen" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="default">
    <meta content="" name="description" />
    <meta content="JonKofee" name="author" />
    <?= Phalcon\Tag::stylesheetLink('assets/plugins/sweet-alert/sweetalert.css');?>
    <?= Phalcon\Tag::stylesheetLink('assets/plugins/pace/pace-theme-flash.css');?>
    <?= Phalcon\Tag::stylesheetLink('assets/plugins/boostrapv3/css/bootstrap.min.css');?>
    <?= Phalcon\Tag::stylesheetLink('assets/plugins/font-awesome/css/font-awesome.css');?>
    <?= Phalcon\Tag::stylesheetLink('assets/plugins/jquery-scrollbar/jquery.scrollbar.css');?>
    <?= Phalcon\Tag::stylesheetLink('assets/plugins/bootstrap-select2/select2.css');?>
    <?= Phalcon\Tag::stylesheetLink('assets/plugins/switchery/css/switchery.min.css');?>
    <?= Phalcon\Tag::stylesheetLink('assets/plugins/bootstrap3-wysihtml5/bootstrap3-wysihtml5.min.css');?>
    <?= Phalcon\Tag::stylesheetLink('assets/plugins/bootstrap-tag/bootstrap-tagsinput.css');?>
    <?= Phalcon\Tag::stylesheetLink('assets/plugins/dropzone/css/dropzone.css');?>
    <?= Phalcon\Tag::stylesheetLink('assets/plugins/bootstrap-datepicker/css/datepicker3.css');?>
    <?= Phalcon\Tag::stylesheetLink('assets/plugins/summernote/css/summernote.css');?>
    <?= Phalcon\Tag::stylesheetLink('assets/plugins/bootstrap-daterangepicker/daterangepicker-bs3.css');?>
    <?= Phalcon\Tag::stylesheetLink('assets/plugins/bootstrap-timepicker/bootstrap-timepicker.min.css');?>
    <?= Phalcon\Tag::stylesheetLink('pages/css/pages-icons.css');?>
    <?= Phalcon\Tag::stylesheetLink('pages/css/pages.css');?>
	<?= Phalcon\Tag::javascriptInclude("assets/plugins/jquery/jquery-1.11.1.min.js");?>
    <!--[if lte IE 9]>
        <link href="pages/css/ie9.css" rel="stylesheet" type="text/css" />
    <![endif]-->
    <script type="text/javascript">
        window.onload = function()
        {
          // fix for windows 8
          if (navigator.appVersion.indexOf("Windows NT 6.2") != -1)
            document.head.innerHTML += '<link rel="stylesheet" type="text/css" href="pages/css/windows.chrome.fix.css" />'
        }
    </script>
</head>