<?php 
$user = Core_UserCenter_Manager::getInstance()->getAccount();
?>

<div class="header">
    <div class="pull-left sm-table">
        <div class="header-inner">
            <div class="brand inline">
            	<img width="78" height="22" data-src-retina="image/logo_2x.png" data-src="image/logo.png" alt="logo" src="image/logo.png">
            </div>
        </div>
    </div>
    <div class=" pull-right">
        <!-- START User Info-->
			<div class="visible-lg visible-md m-t-10">
				<div class="pull-left p-r-10 p-t-10 fs-16 font-heading">
  					<span class="semi-bold">
  						<?= $user->login?>
  					</span>
				</div>
				<div class="dropdown pull-right">
					<button class="profile-dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						<span class="thumbnail-wrapper d32 circular inline m-t-5">
							<img src="image/fox.png" alt="" data-src="image/fox.png" data-src-retina="image/fox.png" width="32" height="32">
						</span>
					</button>
					<ul class="dropdown-menu profile-dropdown" role="menu">
						<li class="bg-master-lighter">
							<a href="#" class="clearfix">
								<span class="pull-left">
									Logout
								</span>
								<span class="pull-right">
									<i class="pg-power"></i>
								</span>
							</a>
						</li>
					</ul>
				</div>
			</div>
        <!-- END User Info-->
	</div>
</div>