<head>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <meta charset="utf-8" />
    <title>Administration control</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <link rel="apple-touch-icon" href="image/60.png">
    <link rel="apple-touch-icon" sizes="76x76" href="image/76.png">
    <link rel="apple-touch-icon" sizes="120x120" href="image/120.png">
    <link rel="apple-touch-icon" sizes="152x152" href="image/152.png">
    <link rel="icon" type="image/x-icon" href="favicon.ico" />
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-touch-fullscreen" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="default">
    <meta content="" name="description" />
    <meta content="JonKofee" name="author" />
    <?= Phalcon\Tag::stylesheetLink('css/pace-theme-flash.css');?>
    <?= Phalcon\Tag::stylesheetLink('css/bootstrap.min.css');?>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <?= Phalcon\Tag::stylesheetLink('css/jquery.scrollbar.css');?>
    <?= Phalcon\Tag::stylesheetLink('css/select2.css');?>
    <?= Phalcon\Tag::stylesheetLink('css/switchery.min.css');?>
    <?= Phalcon\Tag::stylesheetLink('css/pages-icons.css');?>
    <?= Phalcon\Tag::stylesheetLink('css/pages.css');?>
    <?= Phalcon\Tag::stylesheetLink('css/custom.css');?>
    <!--[if lte IE 9]>
        <link href="pages/css/ie9.css" rel="stylesheet" type="text/css" />
    <![endif]-->
    <script type="text/javascript">
        window.onload = function()
        {
          // fix for windows 8
          if (navigator.appVersion.indexOf("Windows NT 6.2") != -1)
            document.head.innerHTML += '<link rel="stylesheet" type="text/css" href="pages/css/windows.chrome.fix.css" />'
        }
    </script>
</head>