<?= Phalcon\Tag::javascriptInclude('assets/plugins/sweet-alert/sweetalert.min.js');?>
<?= Phalcon\Tag::javascriptInclude('assets/plugins/pace/pace.min.js');?>
<?= Phalcon\Tag::javascriptInclude('assets/plugins/modernizr.custom.js');?>
<?= Phalcon\Tag::javascriptInclude('assets/plugins/jquery-ui/jquery-ui.min.js');?>
<?= Phalcon\Tag::javascriptInclude('assets/plugins/boostrapv3/js/bootstrap.min.js');?>
<?= Phalcon\Tag::javascriptInclude('assets/plugins/jquery/jquery-easy.js');?>
<?= Phalcon\Tag::javascriptInclude('assets/plugins/jquery-unveil/jquery.unveil.min.js');?>
<?= Phalcon\Tag::javascriptInclude('assets/plugins/jquery-unveil/jquery.unveil.min.js');?>
<?= Phalcon\Tag::javascriptInclude('assets/plugins/jquery-bez/jquery.bez.min.js');?>
<?= Phalcon\Tag::javascriptInclude('assets/plugins/jquery-ios-list/jquery.ioslist.min.js');?>
<?= Phalcon\Tag::javascriptInclude('assets/plugins/jquery-actual/jquery.actual.min.js');?>
<?= Phalcon\Tag::javascriptInclude('assets/plugins/jquery-scrollbar/jquery.scrollbar.min.js');?>
<?= Phalcon\Tag::javascriptInclude('assets/plugins/bootstrap-select2/select2.min.js');?>
<?= Phalcon\Tag::javascriptInclude('assets/plugins/classie/classie.js');?>
<?= Phalcon\Tag::javascriptInclude('assets/plugins/switchery/js/switchery.min.js');?>
<?= Phalcon\Tag::javascriptInclude('assets/plugins/bootstrap3-wysihtml5/bootstrap3-wysihtml5.all.min.js');?>
<?= Phalcon\Tag::javascriptInclude('assets/plugins/jquery-autonumeric/autoNumeric.js');?>
<?= Phalcon\Tag::javascriptInclude('assets/plugins/dropzone/dropzone.min.js');?>
<?= Phalcon\Tag::javascriptInclude('assets/plugins/bootstrap-tag/bootstrap-tagsinput.min.js');?>
<?= Phalcon\Tag::javascriptInclude('assets/plugins/jquery-inputmask/jquery.inputmask.min.js');?>
<?= Phalcon\Tag::javascriptInclude('assets/plugins/boostrap-form-wizard/js/jquery.bootstrap.wizard.min.js');?>
<?= Phalcon\Tag::javascriptInclude('assets/plugins/jquery-validation/js/jquery.validate.min.js');?>
<?= Phalcon\Tag::javascriptInclude('assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js');?>
<?= Phalcon\Tag::javascriptInclude('assets/plugins/summernote/js/summernote.min.js');?>
<?= Phalcon\Tag::javascriptInclude('assets/plugins/moment/moment.min.js');?>
<?= Phalcon\Tag::javascriptInclude('assets/plugins/bootstrap-daterangepicker/daterangepicker.js');?>
<?= Phalcon\Tag::javascriptInclude('assets/plugins/bootstrap-timepicker/bootstrap-timepicker.min.js');?>
<?= Phalcon\Tag::javascriptInclude('pages/js/pages.min.js');?>
<?= Phalcon\Tag::javascriptInclude('assets/js/scripts.js');?>
<script>
    $(function()
    {
      $('#form-login').validate()
    })
</script>