<?= Phalcon\Tag::javascriptInclude("js/pace.min.js");?>
<?= Phalcon\Tag::javascriptInclude("js/jquery-1.11.1.min.js");?>
<?= Phalcon\Tag::javascriptInclude("js/modernizr.custom.js");?>
<?= Phalcon\Tag::javascriptInclude("js/jquery-ui.min.js");?>
<?= Phalcon\Tag::javascriptInclude("js/bootstrap.min.js");?>
<?= Phalcon\Tag::javascriptInclude("js/jquery-easy.js");?>
<?= Phalcon\Tag::javascriptInclude("js/jquery.unveil.min.js");?>
<?= Phalcon\Tag::javascriptInclude("js/jquery.bez.min.js");?>
<?= Phalcon\Tag::javascriptInclude("js/jquery.ioslist.min.js");?>
<?= Phalcon\Tag::javascriptInclude("js/jquery.actual.min.js");?>
<?= Phalcon\Tag::javascriptInclude("js/jquery.scrollbar.min.js");?>
<?= Phalcon\Tag::javascriptInclude("js/select2.min.js");?>
<?= Phalcon\Tag::javascriptInclude("js/classie.js");?>
<?= Phalcon\Tag::javascriptInclude("js/switchery.min.js");?>
<?= Phalcon\Tag::javascriptInclude("js/jquery.validate.min.js");?>
<?= Phalcon\Tag::javascriptInclude("js/pages.min.js");?>
<?= Phalcon\Tag::javascriptInclude("js/scripts.js");?>
<script>
    $(function()
    {
      $('#form-login').validate()
    })
</script>