<div class="page-sidebar" data-pages="sidebar">
    <div id="appMenu" class="sidebar-overlay-slide from-top"></div>
    <!-- BEGIN SIDEBAR HEADER -->
    <div class="sidebar-header">
        <img src="/image/logo_white.png" alt="logo" class="brand" data-src="/image/logo_white.png" data-src-retina="/image/logo_white_2x.png" width="78" height="22">
        <div class="sidebar-header-controls">
            <button data-pages-toggle="#appMenu" class="btn btn-xs sidebar-slide-toggle btn-link m-l-20" type="button">
            	<i class="fa fa-angle-down fs-16"></i>
            </button>
            <button data-toggle-pin="sidebar" class="btn btn-link visible-lg-inline" type="button">
            	<i class="fa fs-12"></i>
            </button>
        </div>
    </div>
    <!-- END SIDEBAR HEADER -->
    <!-- BEGIN SIDEBAR MENU -->
    <div class="sidebar-menu">
        <ul class="menu-items">
            <li class="m-t-30">
            	<a href="javascript:;">
                    <span class="title">
                    	Places
                    </span>
                    <span class="arrow"></span>
                </a>
                <span class="icon-thumbnail">
                	<i class="fa fa-location-arrow"></i>
                </span>
                <ul class="sub-menu">
                    <li class="">
                        <a href="#">
                        	<span class="title">
                        		List
                        	</span>
                        </a>
                        <span class="icon-thumbnail">
                        	<i class="fa fa-list-ol"></i>
                        </span>
                    </li>
                    <li class="">
                        <a href="#">
                        	<span class="title">
                        		Categories
                        	</span>
                        </a>
                        <span class="icon-thumbnail">
                        	<i class="fa fa-bookmark"></i>
                        </span>
                    </li>
                </ul>
            </li>
            <li class="">
                <a href="javascript:;">
                    <span class="title">
                    	Company
                    </span>
                    <span class="arrow"></span>
                </a>
                <span class="icon-thumbnail">
                	<i class="fa fa-building"></i>
                </span>
                <ul class="sub-menu">
                    <li class="">
                        <a href="/company/manage">
                        	<span class="title">
                        		List
                        	</span>
                        </a>
                        <span class="icon-thumbnail">
                        	<i class="fa fa-list-ol"></i>
                        </span>
                    </li>
                    <li class="">
                        <a href="#">
                        	<span class="title">
                        		Categories
                        	</span>
                        </a>
                        <span class="icon-thumbnail">
                        	<i class="fa fa-bookmark"></i>
                        </span>
                    </li>
                </ul>
            </li>
            <li class="">
                <a href="javascript:;">
                    <span class="title">
                    	Dishs
                    </span>
                    <span class="arrow"></span>
                </a>
                <span class="icon-thumbnail">
                	<i class="fa fa-cutlery"></i>
                </span>
                <ul class="sub-menu">
                    <li class="">
                        <a href="#">
                        	<span class="title">
                        		List
                        	</span>
                        </a>
                        <span class="icon-thumbnail">
                        	<i class="fa fa-list-ol"></i>
                        </span>
                    </li>
                    <li class="">
                        <a href="#">
                        	<span class="title">
                        		Categories
                        	</span>
                        </a>
                        <span class="icon-thumbnail">
                        	<i class="fa fa-bookmark"></i>
                        </span>
                    </li>
                </ul>
            </li>
            <li class="">
                <a href="#">
                    <span class="title">
                    	Tags
                    </span>
                </a>
                <span class="icon-thumbnail">
                	<i class="fa fa-hashtag"></i>
                </span>
            </li>
            <li class="">
                <a href="#">
                	<span class="title">
                		City
                	</span>
                </a>
                <span class="icon-thumbnail">
                	<i class="fa fa-map-marker"></i>
                </span>
            </li>
            <li class="">
                <a href="#">
                	<span class="title">
                		Users
                	</span>
                </a>
                <span class="icon-thumbnail">
                	<i class="fa fa-users"></i>
                </span>
            </li>
            <li class="">
                <a href="#">
                	<span class="title">
                		Feedback
                	</span>
                </a>
                <span class="icon-thumbnail">
                	<i class="fa fa-comment"></i>
                </span>
            </li>
            <li class="">
                <a href="#">
                	<span class="title">
                		Stock
                	</span>
                </a>
                <span class="icon-thumbnail">
                	<i class="fa fa-star"></i>
                </span>
            </li>
        </ul>
    	<div class="clearfix"></div>
    </div>
    <!-- END SIDEBAR MENU -->
</div>