<?= Phalcon\Tag::javascriptInclude('pages/js/pages.min.js');?>
<form role="form" id="addFormCategoryCompany">
  <div class="row">
    <div class="col-sm-12">
      <div class="form-group form-group-default required">
        <label>Name</label>
        <input name="name" type="text" class="form-control" required>
      </div>
    </div>
  </div>
  <button class="hide" type="submit"></button>
</form>

<script>
    $('#submitAddCategoryCompany').unbind('click');
    $('#submitAddCategoryCompany').click(function(){
    	$('#addFormCategoryCompany button[type="submit"]').trigger('click');
    });
    
    $('#addFormCategoryCompany').unbind('submit');
    $('#addFormCategoryCompany').submit(function(e)
    {
		e.preventDefault();
		url = '/categoryCompany/add';
		$.post(
			url,
			$(this).serialize(),
			function(data)
			{
				var data = JSON.parse(data)
				
				table.addRow(data.id, data.name, data.category_id, data.logo, data.datetime_create);
				$('#addModal').modal('hide');
			}
		);
	});
</script>