<?= Phalcon\Tag::javascriptInclude('pages/js/pages.min.js');?>
<form role="form" id="editFormCategoryCompany">
  <div class="row">
    <div class="col-sm-12">
      <div class="form-group form-group-default required">
        <label>Name</label>
        <input name="name" type="text" class="form-control" value="<?= $row->name()?>" required>
      </div>
    </div>
  </div>
  <button class="hide" type="submit"></button>
</form>

<script>
    $('#submitEditCategoryCompany').unbind('click');
    $('#submitEditCategoryCompany').click(function(){
    	$('#editFormCategoryCompany button[type="submit"]').trigger('click');
    });
    
    $('#editFormCategoryCompany').unbind('submit');
    $('#editFormCategoryCompany').submit(function(e)
    {
		e.preventDefault();
		url = '/categoryCompany/edit?id=<?= $row->id()?>';
		$.post(
			url,
			$(this).serialize(),
			function(data)
			{
				location.reload();
			}
		);
	});
</script>