<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <meta charset="utf-8" />
    <title>Login</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <link rel="apple-touch-icon" href="pages/ico/60.png">
    <link rel="apple-touch-icon" sizes="76x76" href="pages/ico/76.png">
    <link rel="apple-touch-icon" sizes="120x120" href="pages/ico/120.png">
    <link rel="apple-touch-icon" sizes="152x152" href="pages/ico/152.png">
    <link rel="icon" type="image/x-icon" href="favicon.ico" />
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-touch-fullscreen" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="default">
    <meta content="" name="description" />
    <meta content="JonKofee" name="author" />
    <?= Phalcon\Tag::stylesheetLink('assets/plugins/pace/pace-theme-flash.css');?>
    <?= Phalcon\Tag::stylesheetLink('assets/plugins/boostrapv3/css/bootstrap.min.css');?>
    <?= Phalcon\Tag::stylesheetLink('assets/plugins/font-awesome/css/font-awesome.css');?>
    <?= Phalcon\Tag::stylesheetLink('assets/plugins/jquery-scrollbar/jquery.scrollbar.css');?>
    <?= Phalcon\Tag::stylesheetLink('assets/plugins/bootstrap-select2/select2.css');?>
    <?= Phalcon\Tag::stylesheetLink('assets/plugins/switchery/css/switchery.min.css');?>
    <?= Phalcon\Tag::stylesheetLink('pages/css/pages-icons.css');?>
    <?= Phalcon\Tag::stylesheetLink('pages/css/pages.css');?>
    <?= Phalcon\Tag::stylesheetLink('assets/css/style.css');?>
    <!--[if lte IE 9]>
        <link href="pages/css/ie9.css" rel="stylesheet" type="text/css" />
    <![endif]-->
    <script type="text/javascript">
    window.onload = function()
    {
      // fix for windows 8
      if (navigator.appVersion.indexOf("Windows NT 6.2") != -1)
        document.head.innerHTML += '<link rel="stylesheet" type="text/css" href="pages/css/windows.chrome.fix.css" />'
    }
    </script>
  </head>
  <body class="fixed-header   ">
    <!-- START PAGE-CONTAINER -->
    <div class="login-wrapper ">
      <!-- START Login Background Pic Wrapper-->
      <div class="bg-pic">
        <!-- START Background Pic-->
        <img src="image/DSC_7904.jpg" data-src="image/DSC_7904.jpg" data-src-retina="image/DSC_7904.jpg" alt="" class="lazy">
        <!-- END Background Pic-->
        <!-- START Background Caption-->
        <div class="bg-caption pull-bottom sm-pull-bottom text-white p-l-20 m-b-20">
          <h2 class="semi-bold text-white">
					Бла бла бла бла</h2>
          <p class="small">
            Что-то снизу написано
          </p>
        </div>
        <!-- END Background Caption-->
      </div>
      <!-- END Login Background Pic Wrapper-->
      <!-- START Login Right Container-->
      <div class="login-container bg-white">
        <div class="p-l-50 m-l-20 p-r-50 m-r-20 p-t-50 m-t-30 sm-p-l-15 sm-p-r-15 sm-p-t-40">
          <img src="image/logo.png" alt="logo" data-src="image/logo.png" data-src-retina="image/logo_2x.png" width="78" height="22">
          <p class="p-t-35">Sign into your pages account</p>
          <!-- START Login Form -->
          <form id="form-login" class="p-t-15" role="form" action="" method="post">
            <!-- START Form Control-->
            <div class="form-group form-group-default">
              <label>Login</label>
              <div class="controls">
                <input type="text" name="username" placeholder="User Name" class="form-control" required>
              </div>
            </div>
            <!-- END Form Control-->
            <!-- START Form Control-->
            <div class="form-group form-group-default">
              <label>Password</label>
              <div class="controls">
                <input type="password" class="form-control" name="password" placeholder="Credentials" required>
              </div>
            </div>
            <!-- START Form Control-->
<!--             <div class="row"> -->
<!--               <div class="col-md-6 no-padding"> -->
<!--                 <div class="checkbox "> -->
<!--                   <input type="checkbox" value="1" id="checkbox1"> -->
<!--                   <label for="checkbox1">Keep Me Signed in</label> -->
<!--                 </div> -->
<!--               </div> -->
<!--             </div> -->
            <!-- END Form Control-->
            <button class="btn btn-primary btn-cons m-t-10" type="submit">Sign in</button>
          </form>
          <!--END Login Form-->
        </div>
      </div>
      <!-- END Login Right Container-->
    </div>
    <!-- END PAGE CONTAINER -->
    <!-- BEGIN VENDOR JS -->
    <?= Phalcon\Tag::javascriptInclude('assets/plugins/pace/pace.min.js');?>
    <?= Phalcon\Tag::javascriptInclude("assets/plugins/jquery/jquery-1.11.1.min.js");?>
    <?= Phalcon\Tag::javascriptInclude('assets/plugins/modernizr.custom.js');?>
    <?= Phalcon\Tag::javascriptInclude('assets/plugins/jquery-ui/jquery-ui.min.js');?>
    <?= Phalcon\Tag::javascriptInclude('assets/plugins/boostrapv3/js/bootstrap.min.js');?>
    <?= Phalcon\Tag::javascriptInclude('assets/plugins/jquery/jquery-easy.js');?>
    <?= Phalcon\Tag::javascriptInclude('assets/plugins/jquery-unveil/jquery.unveil.min.js');?>
    <?= Phalcon\Tag::javascriptInclude('assets/plugins/jquery-unveil/jquery.unveil.min.js');?>
    <?= Phalcon\Tag::javascriptInclude('assets/plugins/jquery-bez/jquery.bez.min.js');?>
    <?= Phalcon\Tag::javascriptInclude('assets/plugins/jquery-ios-list/jquery.ioslist.min.js');?>
    <?= Phalcon\Tag::javascriptInclude('assets/plugins/jquery-actual/jquery.actual.min.js');?>
    <?= Phalcon\Tag::javascriptInclude('assets/plugins/jquery-scrollbar/jquery.scrollbar.min.js');?>
    <?= Phalcon\Tag::javascriptInclude('assets/plugins/bootstrap-select2/select2.min.js');?>
    <?= Phalcon\Tag::javascriptInclude('assets/plugins/classie/classie.js');?>
	<?= Phalcon\Tag::javascriptInclude('assets/plugins/switchery/js/switchery.min.js');?>
    <?= Phalcon\Tag::javascriptInclude("assets/plugins/jquery-validation/js/jquery.validate.min.js");?>
    <!-- END VENDOR JS -->
    <!-- BEGIN CORE TEMPLATE JS -->
    <?= Phalcon\Tag::javascriptInclude('pages/js/pages.min.js');?>
    <!-- END CORE TEMPLATE JS -->
    <!-- BEGIN PAGE LEVEL JS -->
	<?= Phalcon\Tag::javascriptInclude('assets/js/scripts.js');?>
    <!-- END PAGE LEVEL JS -->
    <script>
    $(function()
    {
      $('#form-login').validate()
    })
    </script>
  </body>
</html>