<div class="form-group form-group-default form-group-default-select2">
                        <label>Project</label>
                        <div class="select2-container select2-container-multi full-width" id="s2id_autogen5"><ul class="select2-choices">  <li class="select2-search-field">    <label for="s2id_autogen6" class="select2-offscreen"></label>    <input type="text" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" class="select2-input" id="s2id_autogen6" placeholder="" aria-activedescendant="select2-result-label-104" style="width: 20px;">  </li></ul></div><select class="full-width select2-offscreen" data-init-plugin="select2" multiple="" tabindex="-1">
                          <option value="Jim">Jim</option>
                          <option value="John">John</option>
                          <option value="Lucy">Lucy</option>
                        </select>
                      </div>