<?= Phalcon\Tag::javascriptInclude('pages/js/pages.min.js');?>
<?= Phalcon\Tag::javascriptInclude('assets/plugins/jquery-upload/jquery.iframe-transport.js');?>
<?= Phalcon\Tag::javascriptInclude('assets/plugins/jquery-upload/jquery.fileupload.js');?>
<?= Phalcon\Tag::javascriptInclude('assets/plugins/jquery-upload/jquery.ui.widget.js');?>
<form role="form" id="addFormPlace" enctype="multipart/form-data">
	<div class="row">
		<div class="col col-sm-4">
            <div class="logo_jk">
            	<div data-logo_jk="upload" class="logo_jk_upload-wrap">
            		<div class="logo_jk__upload-outer">
            			<div class="vc-m">
            				<div class="vc-i">
            					<span class="logo_jk__upload-text">
            						<span class="logo_jk__upload-icon">Change image</span>
            					</span>
            				</div>
            			</div>
            		</div>
            	</div>
            	<img id="place-logo" src="https://scontent-frt3-1.cdninstagram.com/hphotos-xft1/t51.2885-19/s150x150/11420849_1597556317176701_1107730959_a.jpg" data-default-src="https://scontent-frt3-1.cdninstagram.com/hphotos-xft1/t51.2885-19/s150x150/11420849_1597556317176701_1107730959_a.jpg" style="width: auto; height: 160px;">
                <input id="logoUpload" name="media" type="file" class="hide" data-url="/media/upload">
                <input id="logo" name="logo" type="text">
            </div>
		</div>
		<div class="col col-sm-8">
          <div class="row">
              <div class="form-group form-group-default required">
                <label>Name</label>
                <input name="name" type="text" class="form-control" required>
              </div>
          </div>
          <div class="row">
              <div class="form-group form-group-default required">
                <label>Address</label>
                <input name="address" type="text" class="form-control" required>
              </div>
          </div>
          <div class="row">
          		<div class="form-group">
                	<input type="hidden" id="company" class="full-width" name="company_id">
                </div>
          </div>
		</div>
	</div>
  <div class="row">
  	<div class="col-sm-12">
  		<div class="form-group">
        	<input type="hidden" id="category" class="full-width" name="category_id">
        </div>
    </div>
  </div>
  <div class="row">
  	<div class="col-sm-12">
  		<div class="form-group">
        	<input type="hidden" id="city" class="full-width" name="city_id">
        </div>
    </div>
  </div>
  <div class="row">
  	<div class="col-sm-12">
      <div class="form-group form-group-default required">
        <label>Geo point</label>
        <input name="geo_point" type="text" class="form-control" required>
      </div>
    </div>
  </div>
  <div class="row">
  	<div class="col-sm-12">
      <div class="form-group form-group-default required">
        <label>Phone</label>
        <input name="phone" type="text" class="form-control" required>
      </div>
    </div>
  </div>
  <div class="row">
  	<div class="col-sm-12">
        <input type="hidden" id="tags" class="full-width" name="tags">
    </div>
  </div>
  <button class="hide" type="submit"></button>
</form>

<script>
function companySelect()
{
	var data = [];
	<?php foreach ($rowsCompany as $company) {?>
		data.push({id: <?= $company->id()?>, text: '<?= $company->name()?>'})
	<?php }?>

	return data
}

function categorySelect()
{
	var data = [];
	<?php foreach ($rowsCategory as $category) {?>
		data.push({id: <?= $category->id()?>, text: '<?= $category->name()?>'})
	<?php }?>

	return data;
}

function citySelect()
{
	var data = [];
	<?php foreach ($rowsCity as $city) {?>
		data.push({id: <?= $city->id()?>, text: '<?= $city->name()?>'})
	<?php }?>

	return data;
}

function tagsInput()
{
	var data = [];
	<?php foreach ($rowsTag as $tag) {?>
		data.push({id: <?= $tag->id()?>, text: '<?= $tag->name()?>'})
	<?php }?>

	return data;
}

    $("#company").select2({
        placeholder: "Company",
        data: companySelect()
    });
    
    $("#category").select2({
        placeholder: "Category",
        data: categorySelect()
    });
    
    $("#city").select2({
        placeholder: "City",
        data: citySelect()
    });
    
    $("#tags").select2({
        placeholder: "Tags",
        multiple: true,
        data: tagsInput()
    });

    $('#submitAddPlace').unbind('click');
    $('#submitAddPlace').click(function(){
    	$('#addFormPlace button[type="submit"]').trigger('click');
    });
    
    $('#addFormPlace').unbind('submit');
    $('#addFormPlace').submit(function(e)
    {
		e.preventDefault();
		url = '/place/add';
		$.post(
			url,
			$(this).serialize(),
			function(data)
			{
				$('#addModal').modal('hide');
				location.reload();
			}
		);
	});

    $('#logoUpload').fileupload({
        dataType: 'json',
        done: function (e, data) {
        	var objImage = data.result;

        	$('#place-logo').attr('src', objImage.path);
        	$('#logo').val(objImage.id);
        }
    });
	
	$('[data-logo_jk="upload"]').click(function(){
		$('#logoUpload').trigger('click');
	});
</script>