<?= Phalcon\Tag::javascriptInclude('assets/plugins/jquery-upload/jquery.fileupload.js');?>
<script src="//api-maps.yandex.ru/2.1/?lang=ru_RU" type="text/javascript"></script>
<form role="form" id="addFormPlace" enctype="multipart/form-data" class="col col-sm-4" style="margin-top: 10px">
	<div class="row">
		<div class="col col-sm-4">
			<div class="logo_jk">
				<div data-logo_jk="upload" class="logo_jk_upload-wrap">
					<div class="logo_jk__upload-outer">
						<div class="vc-m">
							<div class="vc-i">
								<span class="logo_jk__upload-text">
									<span class="logo_jk__upload-icon">Change image</span>
            					</span>
            				</div>
            			</div>
            		</div>
            	</div>
            	<img id="place-logo" src="https://scontent-frt3-1.cdninstagram.com/hphotos-xft1/t51.2885-19/s150x150/11420849_1597556317176701_1107730959_a.jpg" data-default-src="https://scontent-frt3-1.cdninstagram.com/hphotos-xft1/t51.2885-19/s150x150/11420849_1597556317176701_1107730959_a.jpg" style="width: auto; height: 160px;">
                <input id="logoUpload" name="media" type="file" class="hide" data-url="/media/upload">
                <input id="logo" name="logo" type="text">
			</div>
		</div>
		<div class="col col-sm-8">
			<div class="row">
				<div class="form-group form-group-default required">
					<label>Name</label>
					<input name="name" type="text" class="form-control" required>
				</div>
			</div>
    		<div class="row hide">
    			<div class="form-group form-group-default required">
    				<label>Address</label>
    				<input name="address" type="text" class="form-control" required>
    			</div>
    		</div>
    		<div class="row">
    			<div class="form-group">
    				<input type="hidden" id="company" class="full-width" name="company_id">
    			</div>
    		</div>
    		<div class="row">
    			<div class="col-sm-12">
    				<div class="form-group">
    					<input type="hidden" id="category" class="full-width" name="category_id">
    				</div>
    			</div>
    		</div>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-12">
			<div class="form-group">
				<input type="hidden" id="city" class="full-width" name="city_id">
			</div>
		</div>
	</div>
  <div class="row">
  	<div class="col-sm-12">
      <div id="geo" class="form-group form-group-default disabled">
        <label>Geo point</label>
        <input name="geo_point" type="text" class="form-control hide" required>
      </div>
    </div>
  </div>
  <div class="row">
	<div id="map" style="width: 100%; height: 300px;"></div>
  </div>
  <div class="row">
  	<div class="col-sm-12">
      <div class="form-group form-group-default required">
        <label>Phone</label>
        <input name="phone" type="text" class="form-control" required>
      </div>
    </div>
  </div>
  <div class="row">
  	<div class="col-sm-12">
        <input type="hidden" id="tags" class="full-width" name="tags">
    </div>
  </div>
  <button id="submitAddPlace" type="button" class="btn btn-primary" type="submit">Save</button>
</form>

<script>
function companySelect()
{
	var data = [];
	<?php foreach ($rowsCompany as $company) {?>
		data.push({id: <?= $company->id()?>, text: '<?= $company->name()?>'})
	<?php }?>

	return data
}

function categorySelect()
{
	var data = [];
	<?php foreach ($rowsCategory as $category) {?>
		data.push({id: <?= $category->id()?>, text: '<?= $category->name()?>'})
	<?php }?>

	return data;
}

function citySelect()
{
	var data = [];
	<?php foreach ($rowsCity as $city) {?>
		data.push({id: <?= $city->id()?>, text: '<?= $city->name()?>'})
	<?php }?>

	return data;
}

function tagsInput()
{
	var data = [];
	<?php foreach ($rowsTag as $tag) {?>
		data.push({id: <?= $tag->id()?>, text: '<?= $tag->name()?>'})
	<?php }?>

	return data;
}

    $("#company").select2({
        placeholder: "Company",
        data: companySelect()
    });
    
    $("#category").select2({
        placeholder: "Category",
        data: categorySelect()
    });
    
    $("#city").select2({
        placeholder: "City",
        data: citySelect()
    });
    
    $("#tags").select2({
        placeholder: "Tags",
        multiple: true,
        data: tagsInput()
    });

    $('#submitAddPlace').unbind('click');
    $('#submitAddPlace').click(function(){
    	$('#addFormPlace').submit();
    });
    
    $('#addFormPlace').unbind('submit');
    $('#addFormPlace').submit(function(e)
    {
		e.preventDefault();
		url = '/place/add';
		$.post(
			url,
			$(this).serialize(),
			function(data)
			{
				location.href = '/place/manage';
			}
		);
	});

    $('#logoUpload').fileupload({
        dataType: 'json',
        done: function (e, data) {
        	var objImage = data.result;

        	$('#place-logo').attr('src', objImage.path);
        	$('#logo').val(objImage.id);
        }
    });
	
	$('[data-logo_jk="upload"]').click(function(){
		$('#logoUpload').trigger('click');
	});
</script>

<!-- Yandex Maps -->

<script>
	ymaps.ready(function () {
		var myPlacemark;
		var myMap;
		myMap = new ymaps.Map(
				'map', 
				{
					center: [55.751574, 37.573856],
					zoom: 9,
					controls: ['zoomControl', 'searchControl',  'fullscreenControl']
            	},
            	{
                	searchControlProvider: 'yandex#search'
            	}
            );
        
        // Слушаем клик на карте
		myMap.events.add('click', function (e) {
			var coords = e.get('coords');

            ymaps.geocode(coords, {
                results: 1
            }).then(function (res) {
                $('input[name="address"]').val(res.geoObjects.get(0).properties.get('name'));
            });

			$('#geo').find('label').text(coords[0] + '	' + coords[1]);
			$('#geo').find('input').val(coords);

			// Если метка уже создана – просто передвигаем ее
			if (myPlacemark) 
			{
				myPlacemark.geometry.setCoordinates(coords);
            }
            // Если нет – создаем.
            else 
			{
				myPlacemark = createPlacemark(coords);
				myMap.geoObjects.add(myPlacemark);
			}
        });

        // Создание метки
        function createPlacemark(coords) 
        {
            return new ymaps.Placemark(coords,{}, {
                preset: 'islands#circleDotIcon',
                iconColor: 'red'
            });
        }
    });
</script>